spring:
  application:
    name: app
#this requires fro specific spring boot les than 3.5.x
  config:
    import: vault://

  cloud:
    vault:
      uri: http://127.0.0.1:8200
      token: "${Vault_root_Token}"
      kv:
        enabled: true
        backend: secret
        default-context: app

logging:
  level:
    org.springframework.cloud.vault: DEBUG
    org.springframework.vault: DEBUG
