spring:
  data:
    mongodb:
      uri: mongodb://localhost:8191/mydb
  application:
    name: app
#this requires fro specific spring boot les than 3.5.x
#  config:
#    import: vault://
# set VAULT_ADDR and VAULT_TOKEN using export VAULT_ADDR enviornment variablrs
#  cloud:
#    vault:
#      uri: ${VAULT_ADDR}
#      token: ${VAULT_TOKEN}
#      kv:
#        enabled: true
#        backend: secret
#        default-context: app

#logging:
#  level:
#    org.springframework.cloud.vault: DEBUG
#    org.springframework.vault: DEBUG
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: demo-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

